name: lcquickfit_env
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.5.30=h033912b_0
  - libcxx=12.0.1=habf9029_0
  - libffi=3.3=h046ec9c_2
  - llvm-openmp=12.0.1=hda6cdc1_1
  - mkl=2021.3.0=h08c4f10_555
  - mkl-service=2.4.0=py39h89e85a6_0
  - ncurses=6.2=h2e338ed_4
  - openssl=1.1.1l=h0d85af4_0
  - pip=21.2.4=pyhd8ed1ab_0
  - python=3.9.7=hd187cdc_0_cpython
  - python_abi=3.9=2_cp39
  - readline=8.1=h05e3726_0
  - setuptools=58.0.3=py39h6e9494a_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h23a322b_0
  - tbb=2021.3.0=h940c156_0
  - tk=8.6.11=h5dbffcc_1
  - tzdata=2021a=he74cb21_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=haf1e3a3_1
  - zlib=1.2.11=h7795811_1010
  - pip:
    - aesara-theano-fallback==0.0.4
    - arviz==0.11.2
    - astropy==4.3.1
    - astroquery==0.4.3
    - autograd==1.3
    - beautifulsoup4==4.10.0
    - bokeh==2.3.3
    - cachetools==4.2.2
    - celerite2==0.2.0
    - certifi==2021.5.30
    - cftime==1.5.0
    - chainconsumer==0.33.0
    - charset-normalizer==2.0.4
    - cycler==0.10.0
    - datetime==4.3
    - dill==0.3.4
    - exoplanet==0.5.1
    - exoplanet-core==0.1.2
    - fastprogress==1.0.0
    - fbpca==1.0
    - filelock==3.0.12
    - future==0.18.2
    - html5lib==1.1
    - idna==3.2
    - importlib-metadata==4.8.1
    - jinja2==3.0.1
    - joblib==1.0.1
    - keyring==23.1.0
    - kiwisolver==1.3.2
    - ldtk==1.7.0
    - lightkurve==2.0.10
    - llvmlite==0.37.0
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - memoization==0.4.0
    - mimeparse==0.1.3
    - netcdf4==1.5.7
    - numba==0.54.0
    - numpy==1.20.3
    - oktopus==0.1.2
    - packaging==21.0
    - pandas==1.3.2
    - patsy==0.5.1
    - pillow==8.3.2
    - pyerfa==2.0.0
    - pymc3==3.11.4
    - pymc3-ext==0.1.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyvo==1.1
    - pyyaml==5.4.1
    - requests==2.26.0
    - scikit-learn==0.24.2
    - scipy==1.7.1
    - semantic-version==2.8.5
    - semver==2.13.0
    - soupsieve==2.2.1
    - statsmodels==0.12.2
    - tenacity==8.0.1
    - theano-pymc==1.1.2
    - threadpoolctl==2.2.0
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - uncertainties==3.1.6
    - urllib3==1.26.6
    - webencodings==0.5.1
    - xarray==0.19.0
    - zipp==3.5.0
    - zope-interface==5.4.0
prefix: /Users/mason/opt/anaconda3/envs/lcquickfit_env
